# World boundaries
MAX_Y = 8.5
MIN_Y = -8.5
ENEMY_SIZE = 3
BOSS_SIZE = 6

# Boss configuration
BOSS_SPAWN_SCORE_INITIAL = 50
BOSS_HEALTH_MAX = 20
BOSS_DAMAGE = 3
BOSS_POINTS = 5
MIN_ENEMIES_BEFORE_BOSS = 20

# Speed settings
MIN_FLY_SPEED = 4
MAX_FLY_SPEED = 8.0
MIN_BOSS_SPEED = 2.5
MAX_BOSS_SPEED = 4.5
FLY_SPEED_START_SCORE = 20
FLY_SPEED_MAX_SCORE = 100

# Spawn rate
BASE_SPAWN_DELAY = 1.5
MIN_SPAWN_DELAY = 0.5
SPAWN_DELAY_REDUCTION_RATE = 0.002

# Bullet
BULLET_SPEED = 15

# Player
INITIAL_HEALTH = 10